#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

LINT_CMD='npm --prefix ./ui run lint -- --color'

echo "[pre-commit hook] Linting...\n"

if output=$(${LINT_CMD}); then
	exit 0
else
	echo "$output" >&2
	exit 1
fi
