#!/bin/sh
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments. The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, create this file at ".git/hooks/pre-commit" with execute permissions.

UI_DIR_PATTERN='^ui/src/'

git diff --cached --name-only | grep ${UI_DIR_PATTERN} --quiet
IS_UI_CHANGED=$?

if [ ${IS_UI_CHANGED} -ne 0 ]; then
	echo "[pre-commit hook] No UI code changes detected. Skip precommit check."
	exit 0
fi

PRECOMMIT_CMD='npm --prefix ./ui run precommit'

echo "[pre-commit hook] Lint and check formatting...\n"

if output=$(${PRECOMMIT_CMD}); then
	exit 0
else
	echo "$output" >&2
	exit 1
fi
